version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bash -c "chmod +x /code/docker-entry.sh && /code/docker-entry.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
